### ISSUE TITLE
Could not load driver: com.mongodb.jdbc.MongoDriver

### ISSUE THREAD

**Issue by cbirla** [hrishik/solr-mongodb-dih#1]
While executing the data import from Solr Admin portal , it donot index . After checking the solr.log for query status, found the following error.
==> Full Import failed:java.lang.RuntimeException: java.lang.RuntimeException: org.apache.solr.handler.dataimport.DataImportHandlerException: Could not load driver: com.mongodb.jdbc.MongoDriver Processing Document # 1

Please find below the configurations:
Solr : 4.10.2
MongoDB : 2.6.4

solr-config.xml : 
![image](https://cloud.githubusercontent.com/assets/5836486/5161681/41cd3f50-73d5-11e4-88b2-4e0c29a1bfc4.png)

data-config.xml
![image](https://cloud.githubusercontent.com/assets/5836486/5161684/614667e4-73d5-11e4-9fa9-59798150ec8c.png)

Please help me in understanding , why it is not taking the driver, where m i going wrong ?

**Comment by hrishik** [comment]
This must be happening due to mongo JDBC driver not getting picked up by solr. Please validate the paths for your Mongo JDBC jars.
